// <auto-generated />
using System;
using FlowerShop.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowerShop.Infrastructure.Migrations
{
    [DbContext(typeof(FlowerShopDbContext))]
    [Migration("20260330141525_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlowerShop.Domain.Entities.Flower", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FlowerDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlowerImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlowerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Flowers");
                });

            modelBuilder.Entity("FlowerShop.Domain.Entities.FlowerCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FlowerCategories");
                });

            modelBuilder.Entity("FlowerShop.Domain.Entities.FlowerPricing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("FlowerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FlowerId")
                        .IsUnique();

                    b.ToTable("FlowerPrices");
                });

            modelBuilder.Entity("FlowerShop.Domain.Entities.FlowerStock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("FlowerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ImportedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("LastModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("QuantityUnit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlowerId")
                        .IsUnique();

                    b.ToTable("FlowerStocks");
                });

            modelBuilder.Entity("FlowerShop.Domain.Entities.Flower", b =>
                {
                    b.HasOne("FlowerShop.Domain.Entities.FlowerCategory", "Category")
                        .WithMany("Flowers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FlowerShop.Domain.Entities.FlowerPricing", b =>
                {
                    b.HasOne("FlowerShop.Domain.Entities.Flower", null)
                        .WithOne("UnitPrice")
                        .HasForeignKey("FlowerShop.Domain.Entities.FlowerPricing", "FlowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FlowerShop.Domain.ValueObject.EffectiveDate", "PriceEffective", b1 =>
                        {
                            b1.Property<long>("FlowerPricingId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("From")
                                .HasColumnType("datetime2")
                                .HasColumnName("FromDate");

                            b1.Property<DateTime>("To")
                                .HasColumnType("datetime2")
                                .HasColumnName("ToDate");

                            b1.HasKey("FlowerPricingId");

                            b1.ToTable("FlowerPrices");

                            b1.WithOwner()
                                .HasForeignKey("FlowerPricingId");
                        });

                    b.OwnsOne("FlowerShop.Domain.ValueObject.FlowerPrice", "Price", b1 =>
                        {
                            b1.Property<long>("FlowerPricingId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("UnitPrice");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("UnitPriceCurrency");

                            b1.HasKey("FlowerPricingId");

                            b1.ToTable("FlowerPrices");

                            b1.WithOwner()
                                .HasForeignKey("FlowerPricingId");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("PriceEffective")
                        .IsRequired();
                });

            modelBuilder.Entity("FlowerShop.Domain.Entities.FlowerStock", b =>
                {
                    b.HasOne("FlowerShop.Domain.Entities.Flower", null)
                        .WithOne("Stock")
                        .HasForeignKey("FlowerShop.Domain.Entities.FlowerStock", "FlowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlowerShop.Domain.Entities.Flower", b =>
                {
                    b.Navigation("Stock")
                        .IsRequired();

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("FlowerShop.Domain.Entities.FlowerCategory", b =>
                {
                    b.Navigation("Flowers");
                });
#pragma warning restore 612, 618
        }
    }
}
